# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_itemlink_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemlink',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
