# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_auto_20160830_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='main1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='main2',
            field=models.BooleanField(default=False),
        ),
    ]
