# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 05:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_auto_20160830_0812'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='brand',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
