# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_auto_20160831_0517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemlink',
            name='source_url',
            field=models.CharField(max_length=256),
        ),
    ]
